
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 575874
	#The name of the modpack
	modpackName = "Greed The Resource 3 - Factory"
	#The version of the modpack
	modpackVersion = "V9.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

